<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <DefineConstants>TRACE;AVALONIA_BROWSER;</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <DefineConstants>AVALONIA_BROWSER;</DefineConstants>
        <RunAOTCompilation>true</RunAOTCompilation>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>link</TrimMode>

        <WasmStripILAfterAOT>true</WasmStripILAfterAOT>
        <OptimizationPreference>Speed</OptimizationPreference>
        <HybridGlobalization>true</HybridGlobalization>
        <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
        <DebuggerSupport>false</DebuggerSupport>
        <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
        <EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
        <EventSourceSupport>false</EventSourceSupport>
        <Http3Support>false</Http3Support>
        <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
        <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
        <MetricsSupport>false</MetricsSupport>
        <StackTraceSupport>false</StackTraceSupport>
        <UseSizeOptimizedLinq>true</UseSizeOptimizedLinq>
        <UseSystemResourceKeys>true</UseSystemResourceKeys>
        <XmlResolverIsNetworkingEnabledByDefault>false</XmlResolverIsNetworkingEnabledByDefault>
    </PropertyGroup>

    <!--
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <WasmEnableThreads>true</WasmEnableThreads>
    </PropertyGroup>
    -->
    
    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)"/>
        <PackageReference Include="Injectio" Version="5.1.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference OutputItemType="Analyzer" ReferenceOutputAssembly="false" Include="..\Dependencies\ReOsuStoryboardPlayer.Avalonia.SourceGenerator\ReOsuStoryboardPlayer.Avalonia.SourceGenerator.csproj"/>
        <ProjectReference Include="..\ReOsuStoryboardPlayer.Avalonia\ReOsuStoryboardPlayer.Avalonia.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\Fonts\NotoSansSC-VariableFont_wght.ttf"/>
        <AvaloniaResource Include="Assets\Fonts\NotoSansSC-VariableFont_wght.ttf"/>
        <None Remove="Assets\test.osz"/>
    </ItemGroup>
</Project>
