<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <PropertyGroup>
        <BuildTime>$(MSBuildThisFileFullPath)$(MSBuildThisFileModifiedTime)</BuildTime>
        <BuildTimeUtc>$([System.DateTime]::Now.ToString("yyyy/M/dd H:mm:ss.fff"))</BuildTimeUtc>
    </PropertyGroup>

    <Target Name="GenerateBuildTimeClass" BeforeTargets="BeforeBuild">
        <WriteLinesToFile File="$(IntermediateOutputPath)BuildTime.cs" Lines="namespace DpMapSubscribeTool { public static class BuildTime { public static string Value = &quot;$(BuildTimeUtc)&quot;%3B } }" Overwrite="true" />
        <ItemGroup>
            <Compile Include="$(IntermediateOutputPath)BuildTime.cs" />
        </ItemGroup>
    </Target>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.1" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
        <PackageReference Include="Avalonia.Skia" Version="12.0.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="AvaloniaDialogs" Version="3.7.0" />

        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.14" />
        <PackageReference Include="DialogHost.Avalonia" Version="0.12.1" />
        <PackageReference Include="DynamicData" Version="9.4.31" />
        <PackageReference Include="FluentAvalonia.ProgressRing" Version="1.69.2" />
        <PackageReference Include="FluentIcons.Avalonia" Version="2.1.324" />
        <PackageReference Include="FluentIcons.Common" Version="2.1.324" />
        <PackageReference Include="Injectio" Version="5.1.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Xaml.Behaviors" Version="12.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\Pages\Play\PlayPageView.axaml.cs">
            <DependentUpon>HomePageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\OpenStoryboard\BrowserOpenStoryboardDialogView.axaml.cs">
          <DependentUpon>BrowserOpenStoryboardDialogView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Dialogs\OpenStoryboard\LoadingDialogView.axaml.cs">
          <DependentUpon>LoadingDialogView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference OutputItemType="Analyzer" ReferenceOutputAssembly="false" Include="..\Dependencies\ReOsuStoryboardPlayer.Avalonia.SourceGenerator\ReOsuStoryboardPlayer.Avalonia.SourceGenerator.csproj" />
        <ProjectReference Include="..\Dependencies\ReOsuStoryboardPlayer\ReOsuStoryboardPlayer.Core\ReOsuStoryboardPlayer.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="UI\Controls\StoryboardPlayer.axaml" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="SourceGenerator\" />
    </ItemGroup>
</Project>
